[package]
name = "w5500-hl"
version = "0.1.0-alpha.2"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
repository = "https://github.com/newAM/w5500-hl-rs"
license = "MIT"
description = "Driver for the Wiznet W5500 internet offload chip."
readme = "README.md"
keywords = ["spi", "driver", "embedded-hal-driver", "W5500", "wiznet"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/newAM/w5500-hl-rs"

[badges]
maintenance = { status = "experimental" }

[dependencies]
nb = "^1"

[dependencies.w5500-ll]
default-features = false
version = "~0.5.1"
features = ["embedded-hal"]

[dev-dependencies]
version-sync = "~0.9.1"
embedded-hal-mock = "~0.7"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
members = ["testsuite", "testsuite-peer", "testsuite-assets"]
